# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_mailer:
    sender:
        name: Example.com
        address: no-reply@example.com
    emails:
        order_confirmation:
            subject: sylius.emails.order_confirmation.subject
            template: "@SyliusCore/Email/orderConfirmation.html.twig"
