# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

default:
    suites:
        api_managing_promotions:
            contexts:
                - sylius.behat.context.hook.doctrine_orm

                - sylius.behat.context.transform.channel
                - sylius.behat.context.transform.lexical
                - sylius.behat.context.transform.promotion
                - sylius.behat.context.transform.shared_storage

                - sylius.behat.context.setup.channel
                - sylius.behat.context.setup.promotion
                - sylius.behat.context.setup.admin_api_security

                - sylius.behat.context.api.admin.managing_promotions

            filters:
                tags: "@managing_promotions && @api"
